# Generated by Django 2.0.2 on 2019-01-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knack',
            name='type',
            field=models.CharField(choices=[('share', '分享'), ('help', '求助'), ('advice', '建议')], default='', max_length=20, verbose_name='类型'),
        ),
    ]
